#!/usr/bin/perl
use strict;
use warnings;
use 5.010;

if (@ARGV == 2)
{
    die "$ARGV[0] is not file.\n" unless -f $ARGV[0];

    unless (-d $ARGV[1])
    {
        symlink $ARGV[0], $ARGV[1] or die "Error : $!";
    }
    else
    {
        print "I Don't know :( \n";
    }
}
