#!/usr/bin/perl
use strict;
use warnings;
use 5.010;
use File::Copy;

my $dir;
my @dirtree;
my $directory;

$directory = "c:\\test";

opendir ($dir, $directory); 

foreach (readdir ($dir))
{

	print $directory . "\\" . $_;

	next LINE if $_ eq "." or $_ eq "..";
	
	if (-d $directory . "\\" . $_ == 1)
	{
		print " : folder";

		$directory = $directory . "\\" . $_;
	}
	else
	{
		print " : file";

		push ( @dirtree, $directory."\\".$_);
	}

	print "\n";
}

foreach (@dirtree)
{
	print $_ . "\n";
}
