CC := javac

PROGRAM := exam.class GameLauncher.class Dog.class Books.class Hobbits.class DogTestDrive.class

all: $(PROGRAM)

exam.class: exam.java
	$(CC) $^ 

GameLauncher.class: GameLauncher.java
	$(CC) $^ 

Dog.class: Dog.java
	$(CC) $^ 

Books.class: Books.java
	$(CC) $^ 

Hobbits.class: Hobbits.java
	$(CC) $^ 

DogTestDrive.class: DogTestDrive.java
	$(CC) $^ 

clean:
	rm -rf $(PROGRAM) *.class
